"""
modules/rules_engine.py — Phase 2 Semantic Security Logic

Applies extensible business and security rules to the JSON context payload 
generated by the Context Builder.
"""

import json
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional

# ── Severity Constants ──────────────────────────────────────────
SEVERITY_NONE = 0
SEVERITY_LOW = 1
SEVERITY_MEDIUM = 2
SEVERITY_HIGH = 3

SEVERITY_MAP = {
    SEVERITY_NONE: "NONE",
    SEVERITY_LOW: "LOW",
    SEVERITY_MEDIUM: "MEDIUM",
    SEVERITY_HIGH: "HIGH"
}

# ── Base Architecture ──────────────────────────────────────────

class ContextRule(ABC):
    """
    Extensible abstract base class for defining new semantic rules.
    """
    @abstractmethod
    def evaluate(self, context: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Evaluate context data against rule criteria.
        Returns None if rule doesn't trigger, or dict with {"alert": str, "severity": int}
        """
        pass

# ── Specific Rules ─────────────────────────────────────────────

class UnknownPersonRule(ContextRule):
    def evaluate(self, context: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        if context.get("unknown_count", 0) > 0:
            return {
                "alert": "ALERT: Unknown detected",
                "severity": SEVERITY_HIGH
            }
        return None

class PhoneUsageRule(ContextRule):
    def evaluate(self, context: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        objects = [obj.lower() for obj in context.get("objects", [])]
        # Check if phone is present and at least one person is verified or unknown
        total_people = len(context.get("people", [])) + context.get("unknown_count", 0)
        
        if "cell phone" in objects and total_people > 0:
            return {
                "alert": "WARNING: Phone usage",
                "severity": SEVERITY_MEDIUM
            }
        return None

class CrowdDetectionRule(ContextRule):
    def evaluate(self, context: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        total_people = len(context.get("people", [])) + context.get("unknown_count", 0)
        if total_people > 3:
            return {
                "alert": f"ALERT: Crowd detected ({total_people} subjects)",
                "severity": SEVERITY_LOW
            }
        return None

# ── Core Engine ────────────────────────────────────────────────

class RulesEngine:
    """
    Ingests JSON context, iterates over active rules, and aggregates the severity.
    """
    def __init__(self):
        # Register rules dynamically
        self.active_rules: List[ContextRule] = [
            UnknownPersonRule(),
            PhoneUsageRule(),
            CrowdDetectionRule()
        ]

    def add_rule(self, rule: ContextRule):
        """Append a custom rule into the engine."""
        self.active_rules.append(rule)

    def process_context(self, context_json: str) -> str:
        """
        Evaluate the raw JSON context string against all active rules.
        """
        try:
            context = json.loads(context_json)
        except json.JSONDecodeError:
            return json.dumps({"alerts": ["System Error: Malformed Context"], "severity": "HIGH"})
        
        triggered_alerts = []
        max_severity = SEVERITY_NONE

        for rule in self.active_rules:
            result = rule.evaluate(context)
            if result:
                triggered_alerts.append(result["alert"])
                if result["severity"] > max_severity:
                    max_severity = result["severity"]

        # Formulate output structure
        output = {
            "alerts": triggered_alerts,
            "severity": SEVERITY_MAP[max_severity]
        }
        
        return json.dumps(output, indent=2)

# ── Example Usage ────────────────────────────────────────────────
if __name__ == "__main__":
    
    # 1. Simulate Context output (from our context_builder.py)
    mock_context_calm = json.dumps({
        "people": ["Viven"],
        "unknown_count": 0,
        "objects": ["laptop", "chair"],
        "interactions": ["working on laptop"],
        "timestamp": "2026-04-08T20:50:11.0000"
    })
    
    mock_context_breach = json.dumps({
        "people": ["Viven", "Steve", "Sarah"],
        "unknown_count": 2,
        "objects": ["cell phone", "tv"],
        "interactions": ["using phone", "group activity"],
        "timestamp": "2026-04-08T20:55:00.0000"
    })

    # 2. Deploy Engine
    engine = RulesEngine()
    
    # Evaluate Room A
    print("--- SCENARIO: Normal Working Conditions ---")
    print(engine.process_context(mock_context_calm))
    
    # Evaluate Room B
    print("\n--- SCENARIO: 5 People & Unrecognized Subjects using Phones ---")
    print(engine.process_context(mock_context_breach))
